### PR TITLE
[FIX] translate: don't access non-existing self.lang when error handling

### PR DESCRIPTION
**Pull request by jorenvo**
Loading an invalid PO file [1] makes polib.py raise an IOError. This is caught by TranslationImporter's load. A small typo introduced in 727ef9e0a2ca93089b472eb1313117fee8dc876d made the exception handler error:
```
  File "/odoo/addons/base/models/ir_module.py", line 964, in _update_translations
    self.env['ir.module.module']._load_module_terms(mod_names, filter_lang, overwrite)
  File "/odoo/addons/base/models/ir_module.py", line 1074, in _load_module_terms
    translation_importer.load_file(trans_file, lang)
  File "/odoo/tools/translate.py", line 1238, in load_file
    self.load(fileobj, fileformat, lang, xmlids=xmlids)
  File "/odoo/tools/translate.py", line 1259, in load
    iso_lang = get_iso_codes(self.lang)
AttributeError: 'TranslationImporter' object has no attribute 'lang'
```
[1] e.g. instead of a 'msgid' line followed by a 'msgstr' line have two 'msgid' lines

### CODE REVIEW

**Comment by HydrionBurst** [comment]
Thanks. I also noticed the typo and had a commit in https://github.com/odoo/odoo/pull/124402 to fix the problem.
