### ISSUE TITLE
[13] requirements.txt, psycopg2==2.7.3.1 fail to install using python3.8

### ISSUE THREAD

**Issue by grzekru** [odoo/odoo#42660]
**Impacted versions:**

13

**Steps to reproduce:**

pip3 install -r requirements.txt

**Current behavior:**

Impossible to install all python packages from requirements.txt using pip in virtual environment using Python3.8
```
psycopg/psycopgmodule.c:685:18: error: dereferencing pointer to incomplete type ‘PyInterpreterState’ {aka ‘struct _is’}
```
**Expected behavior:**

Works good after upgrading psycopg2 version in requirements.txt

**Comment by pedrobaeza** [comment]
@d-fence should P3.8 compatibility be excluded explicitly from documentation?

**Comment by Yenthe666** [comment]
I've seen more reports about this scattered around the Odoo channels. I vote for documenting it.

**Comment by mart-e** [comment]
odoo should work in 3.8 (this is the version I am using since #40406). Let's fix packaging instead of documenting.
[In debian](https://packages.debian.org/buster/python3-psycopg2) we have 2.7.7 so we could increase the requirements, to see if it works better.
If we change pyscopg2, be careful it does not break anything else, cf 144a5286163451a348c8697d18e6bd39a77b7e64

**Comment by mileo** [comment]
Same issue here

**Comment by kemier** [comment]
same issue,hope fix it

**Comment by d-fence** [comment]
I have this PR that should fix that : #40361
I need some approbation from @odony because I changed the way babel.dates is imported

**Comment by rjtubera** [comment]
Hi how to fix this one?
