### ISSUE TITLE
[8.0][regression] Problem with computed integer fields

### ISSUE THREAD

**Issue by ludwiktrammer** [odoo/odoo#3972]
An regression exists introduced in commit f2e4a10e1a58c932f9a989e642771f5ae75d756a (on November 3th).

I've got a model with a computed integer field:

    class Foo(models.Model):
        _name = 'my.foo'

        # ...
        age = fields.Integer(compute='compute_age')

        @api.one
        def compute_age(self):
            self.age = 25  # simplified example ;)

When I try to display objects of this model in kanban view (grouped by an entirely different field) I get the following error:

    File "/[snip]/odoo/openerp/models.py", line 2101, in read_group
        if getattr(self._fields[f].base_field.column, '_classic_write')
    AttributeError: 'NoneType' object has no attribute '_classic_write'

The problem didn't exist before commit f2e4a10e1a58c932f9a989e642771f5ae75d756a. It seems that [this is the change that causes the problem](https://github.com/odoo/odoo/commit/f2e4a10e1a58c932f9a989e642771f5ae75d756a#diff-5cd113a636a42f726042abc6798a9efaR2131).

**Comment by mart-e** [comment]
Indeed an inssue with non-stored integer (or float) that could not be aggreated.
It was fixed at 33c8aae

**Comment by nareshppts** [comment]
fbf
