### PR TITLE
[FIX] mail_group: fix error when browsing mailing lists

### PR DESCRIPTION
**Pull request by xavieralt**
To reproduce (on runbot):

- Go to /groups url
- click on "Public Mailing List"

This fix `AttributeError: 'PortalMailGroup' object has no attribute 'env'`
(introduced by odoo/odoo@b60cf1f9777)

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by tde-banana-odoo** [comment]
Isn't it happening at earlier versions ?

**Comment by xavieralt** [comment]
@tde-banana-odoo no saas~16.3+ only, was introduced by https://github.com/odoo/odoo/commit/b60cf1f9777

**Comment by tde-banana-odoo** [comment]
In that case always a good practice to link the original commit in the fix message, so that we can trace a bit the history :)

**Comment by xavieralt** [comment]
I've added the commit ref/link in the PR/commit msg
