### ISSUE TITLE
Odoo does not start on python 3.8

### ISSUE THREAD

**Issue by mikes-gh** [odoo/odoo#42696]
Impacted versions:

Odoo 13.0

Steps to reproduce:

git clone
py odoo-bin

Current behavior:

ImportError: cannot import name 'clock' from 'time' (unknown location)
Due to https://bugs.python.org/issue36895

Expected behavior:

Odoo runs correctly

Note: If I use python 3.7.6 all works well.

**Comment by pedrobaeza** [comment]
There are several issues opened about problems with P3.8, so I'm going to close this one. For now, consider Odoo not compatible with P3.8 (although the documentation doesn't state this explicitly).

**Comment by mikes-gh** [comment]
Is my issues a duplicate.
I couldn't find any issue with the specifics of this one which is why I posted separately to aid fixing.

**Comment by pedrobaeza** [comment]
Not exactly a duplicate, but it's clear that Odoo doesn't work with P3.8. When that support is fixed, it's because it will start with that version, and this is going to arise for sure, so no need IMO to let the issue opened highlighting this. If @d-fence thinks the contrary, please reopen.

**Comment by mikes-gh** [comment]
Also time.clock has been depreciated since 3.3 so there are alternatives since that version so this specific issue can be fixed now and be backwards/forwards compatible >= 3.3 regardless of other 3.8 issues,

**Comment by vysakhbt-git** [comment]
And here I am facing the same issue trying to run Odoo14 on Python 3.9.

**Comment by medosobh** [comment]
the same odoo17 CE comes with P3.8 and in documentation ask to use P3.10..
nightly server provide odoo 17 with P3.8 !!!!!!!!
