### PR TITLE
[FIX] requirements.txt: pin the last version of cryptography

### PR DESCRIPTION
**Pull request by ap-wtioit**
version 37.0.0 of cryptography is no longer working with pyopenssl==19.0.0

Description of the issue/feature this PR addresses:
When running odoo 15.0 (with dependencies installed from requirements.txt) we get the following error:
```
2022-04-27 05:59:27,091 19 CRITICAL ? odoo.modules.module: Couldn't load module web 
2022-04-27 05:59:27,091 19 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK' 
2022-04-27 05:59:27,091 19 ERROR ? odoo.service.server: Failed to load server-wide module `web`.
The `web` module is provided by the addons found in the `openerp-web` project.
Maybe you forgot to add those addons in your addons_path configuration. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1208, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/opt/odoo/custom/src/odoo/odoo/modules/module.py", line 396, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/auto/addons/web/__init__.py", line 4, in <module>
    from . import controllers
  File "/opt/odoo/auto/addons/web/controllers/__init__.py", line 4, in <module>
    from . import main
  File "/opt/odoo/auto/addons/web/controllers/main.py", line 34, in <module>
    from odoo.addons.base.models.ir_qweb import render as qweb_render
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/__init__.py", line 23, in <module>
    from . import ir_mail_server
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
2022-04-27 05:59:27,107 19 CRITICAL ? odoo.modules.module: Couldn't load module base 
2022-04-27 05:59:27,107 19 CRITICAL ? odoo.modules.module: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK' 
2022-04-27 05:59:27,107 19 ERROR ? odoo.service.server: Failed to load server-wide module `base`. 
Traceback (most recent call last):
  File "/opt/odoo/custom/src/odoo/odoo/service/server.py", line 1208, in load_server_wide_modules
    odoo.modules.module.load_openerp_module(m)
  File "/opt/odoo/custom/src/odoo/odoo/modules/module.py", line 396, in load_openerp_module
    __import__('odoo.addons.' + module_name)
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/__init__.py", line 5, in <module>
    from . import models
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/__init__.py", line 23, in <module>
    from . import ir_mail_server
  File "/opt/odoo/custom/src/odoo/odoo/addons/base/models/ir_mail_server.py", line 19, in <module>
    from OpenSSL import crypto as SSLCrypto
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/__init__.py", line 8, in <module>
    from OpenSSL import crypto, SSL
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1553, in <module>
    class X509StoreFlags(object):
  File "/usr/local/lib/python3.8/site-packages/OpenSSL/crypto.py", line 1573, in X509StoreFlags
    CB_ISSUER_CHECK = _lib.X509_V_FLAG_CB_ISSUER_CHECK
AttributeError: module 'lib' has no attribute 'X509_V_FLAG_CB_ISSUER_CHECK'
```

Current behavior before PR:
when installing requirements the installed versions of pyOpenSSL(==19.0.0) and cryptography(==37.0.0) are not compatible with each other

Desired behavior after PR is merged:
when installing requirements the installed versions of pyOpenSSL(==19.0.0) and cryptography(==36.0.2) are compatible with each other

Info @wt-io-it

Thanks to @moylop260 for tweeting about the issue, so i could fix it faster (for us):
[https://twitter.com/moylop260/status/1519123563760033794](https://twitter.com/moylop260/status/1519123563760033794)

--
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by ap-wtioit** [comment]
This seems also related to https://github.com/odoo/odoo/issues/79697

**Comment by MiquelRForgeFlow** [comment]
ping @d-fence

**Comment by yostashiro** [comment]
Switched cryptography from 37.0.2 to 36.0.2 and still getting this warning in my environment.

**Comment by Yenthe666** [comment]
@d-fence we either need this or an upgrade of `pyopenssl` :)
Gives errors on Ubuntu 22.04 with Odoo 16 too.

**Comment by Xavier-Do** [comment]
I think that a cleaner fix would be to pin pyopenssl to 21.0.0 (for python > 3.9) since it is the package version in [ubuntu jammy](https://packages.ubuntu.com/hu/jammy/python3-openssl).

We actually downgrade pyopenssl to 19.0 with the requirement and it could be cleaner to test it with the latest version in ubuntu jammy. 
But we may also need to adapt some code in case of deprecation warning/ api changes. We can test this branch on jammy to ensure it is working to avoid discovering the error during the forwardport to 16.0.

We are currently investigating on why this is working on runbot. For some reason we have a [cryptography 3.4](https://runbot.odoo.com/runbot/versions)

I cannot confirm this is the fix we will choose but it could be a good idea to test it. I'll change the dockerfile of this branch to jammy so that we can test it :)

**Comment by Xavier-Do** [comment]
Gevent does not install, your branch is actually 1500 commit behind and does not have the last requirements.

Cryptography is actually already pined ...
`cryptography==3.4.8`

This is why you have conflict with this branch.
