### ISSUE TITLE
[13.0] Odoo not compatible with Python 3.9

### ISSUE THREAD

**Issue by Yenthe666** [odoo/odoo#71352]
Impacted versions: At least 13.0/14.0 but I assume all.

Steps to reproduce:
1. Setup a new server which runs Python 3.9
2. Install Odoo 13
3. Try to create a databae

Current behavior:
The database creation fails almost directly saying:
```
File "/odoo13/odoo13-server/odoo/addons/base/models/ir_ui_menu.py", line 70, in read_image
    icon_image = base64.encodestring(icon_file.read())
odoo.tools.convert.ParseError: "module 'base64' has no attribute 'encodestring'" while parsing /odoo13/odoo13-server/odoo/addons/base/views/base_menus.xml:2
```
This is because in Python <= 3.8 you could do:
```
import base64
base64.encodestring(some_object.read())
```

However, if you run the same in Python 3.9 you will get `module 'base64' has no attribute 'encodestring'`.
This is because since 3.9 you need to do 
```
from base64 import encodebytes as encodestring
```

Offending line in V13:
https://github.com/odoo/odoo/blob/2e0127af0d283d1d9bdb033de356e2ddf0973cce/odoo/addons/base/models/ir_ui_menu.py#L70
Fixed in V14:
https://github.com/odoo/odoo/blob/c76d1a0f0210565768c88271625212359720632e/odoo/addons/base/models/ir_ui_menu.py#L69

Expected behavior: Odoo 13 works fine with Python 3.9.

**Comment by Yenthe666** [comment]
@Julien00859 I see you made loads of fixes against this in V14 at https://github.com/odoo/odoo/commit/4f03a5f136ab928ae74322bf1c34a1b6a6baf979.
Any chance we can get backports for this in V13?

**Comment by Julien00859** [comment]
What a bunch of liars at Python, they promised to send deprecation warnings in 3.9 and to only remove the stuff in 3.10, I'll look at it tomorrow

**Comment by xmo-odoo** [comment]
> What a bunch of liars at Python, they promised to send deprecation warnings in 3.9 and to only remove the stuff in 3.10, I'll look at it tomorrow

decostring and encodestring have been deprecated since 3.1.
