### ISSUE TITLE
[Odoo 13] Any field I try to change creates a error message

### ISSUE THREAD

**Issue by hhassey** [odoo/odoo#40055]
Impacted versions:
13
Steps to reproduce:
Go to any field try to put in a value.
Error message pops, and after accepting the error message it takes the value with no further problems.

Current behavior:
Error message pops up. with this message
Error:

Traceback:
_onFieldChanged@http://XX.XX.XX.XX:8069/web/content/854-18e96aa/web.assets_backend.js:1616:1230
_onFieldChanged@http://XX.XX.XX.XX:8069/web/content/854-18e96aa/web.assets_backend.js:1374:35
proxy/<@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:3950:11
trigger@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:3948:180
_trigger_up@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:3954:378
_trigger_up@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:3954:462
_trigger_up@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:3954:462
trigger_up@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:3954:280
_setValue/<@http://XX.XX.XX.XX:8069/web/content/854-18e96aa/web.assets_backend.js:823:104
MyPromise/promise<@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:71:230
MyPromise@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:71:13
_setValue@http://XX.XX.XX.XX:8069/web/content/854-18e96aa/web.assets_backend.js:823:22
reinitialize@http://XX.XX.XX.XX:8069/web/content/854-18e96aa/web.assets_backend.js:987:265
select@http://XX.XX.XX.XX:8069/web/content/854-18e96aa/web.assets_backend.js:989:511
_trigger@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1408:75
menuselect@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1857:17
handlerProxy@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1403:61
dispatch@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1030:447
add/elemData.handle@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1016:166
trigger@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1247:227
trigger/<@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1253:258
each@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:729:170
each@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:720:192
trigger@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1253:229
_trigger@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1408:14
select@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1844:6
$.widget/</proxiedPrototype[prop]</<@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1378:159
click .ui-menu-item@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1817:1108
handlerProxy@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1403:61
dispatch@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1030:447
add/elemData.handle@http://XX.XX.XX.XX:8069/web/content/851-f28b1bc/web.assets_common.js:1016:166

Expected behavior:
No error message should pop

Video/Screenshot link (optional):
![odoo error](https://user-images.githubusercontent.com/12564379/68496655-b1d87100-0207-11ea-9bf1-655d8c839b8a.png)

**Comment by Yenthe666** [comment]
Hi @hhassey,

Thanks for the report. Can you also reproduce this on the official test instances from Odoo at runbot.odoo.com? I also see that you're using a custom theme. Are you sure the issue is not in there as this is a JS issue? ;)

Regards,
Yenthe

**Comment by hhassey** [comment]
Thanks @Yenthe666 , yes I am sure the theme is not the source, I actually installed it in the hopes that the JS problem would go away.

**Comment by pedrobaeza** [comment]
Then please try to reproduce the problem in runbot infrastructure (http://runbot.odoo.com/runbot - admin/admin)?

If so, please explain with all the possible detailed steps to get to the error. Not having them, it's very difficult to hunt down the problem. Please don't be shy of adding details, and even better if you provide some screenshots or videos.

If not, this can be due to a configuration change, a custom/community module you have deployed in your DB or an outdated code. Please report back if it's the case.

For keeping a clean house in this issue tracker, if you don't answer in several days, this will be closed assuming it was one of the stated things.

**Comment by hhassey** [comment]
@Yenthe666 @pedrobaeza Confirmed, the error also afects runbot infrastructure install.
tried this one: (http://683235-13-0-5a595c.runbot26.odoo.com/) .

Client OS: Debian Buster
Browser: 
 * Firefox ESR 68.2.0esr (64-bit)
 * Chrome with same results. 
I am trying to test a Windows setup but will take me about an hour while since I don't have a WS computer handy. I will report when I can get it done

Screencast Attached:
[vokoscreen-2019-11-08_12-43-23.zip](https://github.com/odoo/odoo/files/3826214/vokoscreen-2019-11-08_12-43-23.zip)

**Comment by pedrobaeza** [comment]
I have just tried on runbot and I don't get the problem. I suspect that Firefox ESR, being an old version, it's not compatible with latest JS, and Chrome should be as well outdated.

Any way, this is not something of Odoo itself, but your browsers, so closing.

**Comment by hhassey** [comment]
@pedrobaeza Confirmed, with the latest Firefox the error goes away. I am sorry that I have wasted your time with this issue, but I am very grateful that you responded so fast.

Sorry Again.

**Comment by pedrobaeza** [comment]
You're welcome. There's no waste if the issuer provides enough information, understands the issue tracker flows and solves their problem.

**Comment by jlegido** [comment]
Hi there.

First of all many thanks everybody involved in maintaining Odoo for your time.

I'm facing same issue with Odoo 13 and Firefox (68.2.0esr-1+b1) but it's working fine with Chromium (76.0.3809.100-1).

I think worth investing some time to check error:

```
TypeError: this._applyChanges(...).then(...).guardedCatch is not a function web.assets_backend.js:1616:1230
```

My point is that I don't consider, for instance, 68.x an outdated version of Firefox, thus there are more chances that people are facing same issue.

Thanks again.

**Comment by PismennyiIgor** [comment]
The same problem with odoo 13 and Firefox (68.2.0esr-68.3.0esr).
Firefox 68.3.0 ESR isn't old version. Release date - December 3, 2019
From official website mozilla.org.
(Firefox offers an Extended Support Release (ESR) for organizations, including schools, universities, businesses and others who need extended support for mass deployments. The ESR release is based on the regular release cycle of Firefox for desktop. )
