### PR TITLE
[FIX] html_editor: no dependency on http_routing

### PR DESCRIPTION
**Pull request by kmagusiak**
The dependency is wrong. The function
`_get_translation_frontend_modules_name` is simply dead code.

Issue introduced in #287134

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by Julien00859** [comment]
http_routing is the common ancestor of portail and website. html_editor is not concerned with it.

@robodoo r+

**Review by adr-odoo — APPROVED** [review]
This fixes a style compilation error on the login page when using a database without the module installed. Thanks!
