### ISSUE TITLE
v9 broken with lessc in Debian unstable (=1.6.3~dfsg-1)

### ISSUE THREAD

**Issue by mistotebe** [odoo/odoo#9113]
**Odoo v9 web client is broken with latest lessc**

Impacted versions:

 - 9.0

Steps to reproduce:

 1. Install a fresh Debian unstable and all Odoo dependencies
 2. create a new database
 3. Log in to said database

Current behaviour:

 - Odoo css generation fails with "TypeError: CleanCSS is not a function".

Expected behaviour:

 - A full user interface loads as expected.

Downgrading node-less to 1.4.2-1 (previous version) fixes the issues. Not sure if Odoo, lessc or its Debian packaging is at fault.

**Comment by fasser** [comment]
Confirmed: odoo 9.0.20151027 fails with debian's node-less 1.6.3~dfsg-1 (stretch), but works OK with 1.4.2-1 (jessie).

**Comment by grexe** [comment]
can confirm with latest nightly 9.0c.20160310 still.

**Comment by grexe** [comment]
any update on this? It's quite annoying to keep the node-less package pinned to an old version, I'd rather keep my system up-to-date... seems like a quick fix, or not?

**Comment by max3903** [comment]
Same issue on Ubuntu 16.04.

**Comment by AlexBander** [comment]
Confirmed: odoo 9.0c.20160421 fails with debian(stretch) and node-less 1.6.3~dfsg-2

**Comment by gfcittolin** [comment]
Confirmed with odoo 9.0-20151010. Downgrading just the node-less package (.deb) hasn't work for me, as the package/folder structure has changed. Had to manually link the /usr/lib/nodejs/less/lib/less folder to the 1.4.2 version downloaded separately

**Comment by krnkris** [comment]
Same problem:
odoo 9.0c.20160421  and node-less 1.6.3~dfsg-2, fails

**Comment by MohamedYousof** [comment]
Same on Ubuntu 16.04 using Odoo from source grabbed from github.com

**Comment by sylvain-garancher** [comment]
It seems that the nodejs "clean-css" module is not found.

When removing the CSS cleaning argument of the lessc command, everything works.
```patch
diff --git a/openerp/addons/base/ir/ir_qweb.py b/openerp/addons/base/ir/ir_qweb.py
index e777616..32b75fa 100644
--- a/openerp/addons/base/ir/ir_qweb.py
+++ b/openerp/addons/base/ir/ir_qweb.py
@@ -1682,7 +1682,7 @@ class LessStylesheetAsset(PreprocessedCSS):
         except IOError:
             lessc = 'lessc'
         lesspath = get_resource_path('web', 'static', 'lib', 'bootstrap', 'less')
-        return [lessc, '-', '--clean-css', '--no-js', '--no-color', '--include-path=%s' % lesspath]
+        return [lessc, '-', '--no-js', '--no-color', '--include-path=%s' % lesspath]
 
 def rjsmin(script):
     """ Minify js with a clever regex.
```

**Comment by krnkris** [comment]
Yes it seem the cache cleaning not succeeding, because 
the firs page  - let say the database selector - is looks good, but after the selection
all is a disaster...

**Comment by Yenthe666** [comment]
@sylvain-garancher same issue on Ubuntu 16.04.
Your patch does not fix the issue.. Can you have another look?

**Comment by daniel-adb-fa** [comment]
Running on Ubuntu 16.04 here, too, and encountered the same bug. However, disabling clean-css works for me.

**Comment by CarlesAntoli** [comment]
In Ubuntu 16.04 and odoo 9 i uninstalled cleancss and I have reinstalled with:
sudo npm install -g less less-plugin-css-and-clean && sudo ln -s /usr/bin/nodejs/usr/bin/node and it works correctly.

**Comment by krnkris** [comment]
In my case I cleared/removed all symlinks 
(like this (sudo ln -s /usr/bin/nodejs /usr/bin/node)
in UBUNTU 16.04
then I deleted with synaptic the nodejs, npm , less, less-plugin-clean-css 
then
reinstalled:
sudo apt-get install nodejs
sudo apt-get install npm
sudo npm install -g less
sudo npm install -g less-plugin-clean-css

I had to run two times the 
sudo npm install -g less
sudo npm install -g less-plugin-clean-css

because first time the clean-css directory was not created & working properly.

Hope it's helps.

odoo 9.0c.20160424 and node-less 1.6.3~dfsg-2, Ubuntu 16.04, NOW WORKING
BTW.: not all browsers working with it (Firefox, Safari works  -   Firefox Nightly, Aurora did not work)

**Comment by lukebranch** [comment]
@krnkris ,

Thanks for the steps. In my case I followed your instructions and got up to the following lines:
sudo npm install ­-g npm
sudo npm install ­g less less­-plugin­-clean­-css

I had the following error on a clean Ubuntu 16.04 install when running the above commands:

/usr/bin/eng: 'node': No such file or directory

to get it working I needed to add the following symlinks:

sudo ln -s /usr/local/bin/lessc /usr/bin/lessc
sudo ln -s /usr/bin/nodejs /usr/bin/node

and then run those npm commands again:

sudo npm install -g less
sudo npm install -g less-plugin-clean-css

This seemed to work in my case.

**Comment by Yenthe666** [comment]
@lukebranch thanks for posting this, I just ran in to this issue too. After executing your commands everything works fine (after a -u all of the database).
It looks like the symlinks aren't attached well so that Odoo can't find them.
@sle-odoo if you want a really easy way to simulate this you can use my installation script (https://github.com/Yenthe666/InstallScript/blob/All/odoo_install.sh).
Information about how to use it can be found here: https://github.com/Yenthe666/InstallScript/tree/All

**Comment by lukebranch** [comment]
@Yenthe666 ,

no problem, glad it helped.

**Comment by oliverzgy** [comment]
follow the official instruction and do the additional below
/usr/bin/lessc -> ../lib/nodejs/less/bin/lessc  remove this symbolic link and add 
/usr/bin/lessc -> ../lib/node_modules/less/bin/lessc

**Comment by lukebranch** [comment]
@oliverzgy ,

Thanks for the suggestion, although in Ubuntu 16.04 with a vanilla installation and having run Yenthe's script, I don't have that symlink:

/usr/bin/lessc -> ../lib/nodejs/less/bin/lessc

and:

/usr/lib/node_modules

does not exist either. 

Perhaps i'm missing something. Could you list your installation steps so that I can compare?

**Comment by sle-odoo** [comment]
@Yenthe666 An even more easy way to simulate the issue is to install our official debian package. The issue is in the packages from Debian: they somehow made their bundled plugin-clean-css not discoverable by their bundled lessc. We have to file a ticket on their bug tracker...

I'll discuss what we should do in the meantime. Sadly, there's no lessc command to list the lessc plugins and npm packages could be installed locally or globally. I think the correct workaround would be to compile a css file with the minification at the startup of Odoo and, if it fails, disable the minification but let the compilation from lessc work (if lessc is found).

**Comment by DGEAPerez** [comment]
Hi.. Here i'm using Ubuntu 16.04... I did every step you suggest whitout success...

Please, tell me what you need to provide to guide me to solve this issue...

Thanks...

**Comment by lukebranch** [comment]
@DGEAPerez ,

Could you list out the steps you have followed in chronological order (ie. steps to reproduce).

**Comment by krnkris** [comment]
Steps UBUNTU 16.04

Remove all about nodejs + npm

sudo apt-get purge nodejs
sudo apt-get autoremove



Then in a NEW terminal follow these steps:
/Don't interrupt, just follow step-by-step/

curl -sL https://deb.nodesource.com/setup_0.12 | sudo bash -
sudo apt-get install nodejs npm

sudo npm install -g less-plugin-clean-css less
sudo  npm install -g clean-css
sudo npm install -g less
sudo npm install -g less-plugin-clean-css

sudo npm install ­-g npm
sudo npm install -g less less-plugin-clean-css

sudo apt-get install node-less

sudo ln -s /usr/bin/nodejs /usr/bin/node

Hope it helps....

After all the steps, you clear the browser cache + make a new database
in ODOO.
The new database would be OK. The old one in my case looks bad...

**Comment by daniel-adb-fa** [comment]
The following steps worked for deploying odoo on Ubuntu 16.04:

1. Install odoo 9.0 from the nightly repo according to documentation.
2. Install the current versions of less and less-plugin-css via npm. This will install the versions to /usr/local/bin:
`npm install -g less less-plugin-clean-css`
3. Install the symlink /usr/bin/node. This can be done manually, but you can also use an official apt-package for it:
`apt install nodejs-legacy`
4. Now the link to lessc has to be patched to point to the version installed by npm instead of the (broken) distribution version:
`rm /usr/bin/lessc; ln -s /usr/local/bin/lessc /usr/bin/lessc`
5. This should work, but an update of the distribution package might still break the patched link later. To avoid this, I did `apt-mark hold node-less`.

Of course, restart the odoo service and don't forget to clear your browser cache after that.

Hope this helps.

**Comment by DGEAPerez** [comment]
@lukebranch I followed the steps from these places:
https://www.odoo.com/documentation/9.0/setup/install.html#packaged-installers
https://www.linode.com/docs/websites/cms/install-odoo-9-erp-on-ubuntu-14-04
https://www.odoo.com/es_ES/forum/ayuda-1/question/how-can-i-install-odoo-9-88323

Using the common sense: I used the last two to clarify the official documentation...

When see the error about the "less" thing I arrived here and I did everything you can read above without success...

@krnkris I followed each step, when purge nodejs it charged odoo installation too.. Then be caarefull who follow those steps... BTW, it didn't fix the problem...

@daniel-adb-fa steps 3 and 4 seems to do the magic... Now I can see the applications manager...

Thanks to all

**Comment by AzzedineOuali** [comment]
I've also tried all the steps above and it doesn't work but @daniel-adb-fa's solution (step 3 and 4) fixed the issue.
big thanx.

**Comment by thnuder** [comment]
same thing for me @daniel-adb-fa solve the issue

**Comment by dvrles001** [comment]
@daniel-adb-fa Thanks your solution worked for us

**Comment by krnkris** [comment]
@daniel-adb-fa Thanks your solution worked 
FYI:
I reinstalled ubuntu 16.04 
in this case all differ conflicted system files cleared out.
/I was upgraded from 14.04 before/

Thank you again.

**Comment by blaggacao** [comment]
@sle-odoo What do you think of an independently callable "compile" script for lessc and css-clean do it's work so we can drop those dependency completely at runtime. nodejs/npm are beasty candidates in their footprint...

**Comment by blaggacao** [comment]
Best answer: https://github.com/odoo/odoo/issues/9113#issuecomment-217795632
`apt-get install -y --no-install-recommends npm && npm install -g less less-plugin-clean-css`

I could drop step 3 through 5 entirely. And if not so, why use `--prefix=/usr` after the `-g` flag?

**Comment by sle-odoo** [comment]
@blaggacao we are going to remove the clean-css dependency by minifying ourselves the css. Replacing lessc is not trivial.

**Comment by blaggacao** [comment]
@sle-odoo I meant not replace it entirely, I mean make it a *buildtime* dependency, rather than a *runtime*. In a docker it would look like that you would just compile all `.less` files to `.css` files and then elegantly move node out of the way so that the shipped image has the finished `.css` files but no beasty node.
Or would this conflict with app store loaded modules? However I think on the appstore end care can be taken by maintainers to avoide node dependencies.

**Comment by sle-odoo** [comment]
Lessc is a runtime dependency: when you install a new addon, it's possible that this new addon extends the bundle and then we need to invalidate and recompile the bundle. It is also possible to invalidate the bundle by creating an xpath manually in the webclient, etc. So you cannot do it this way.

**Comment by sle-odoo** [comment]
So, the removal of clean-css has been merged in stable. I'm closing this issue as i just tested in Ubuntu Xenial and it's working, and it should be the same for Debian >= Jessie.

Regards

**Comment by alaherma** [comment]
Hey this issua apeared again in odoo 10

**Comment by SalahAdDin** [comment]
It happens in 11.0, it is possible.
