### PR TITLE
[FIX] website: redirect to website page if configurator_done is true

### PR DESCRIPTION
**Pull request by chdh-odoo**
**Steps to reproduce:**
1. Go to definition of default_website and add `<field name="configurator_done" eval="True"/>` .
2. install website module.

**Issue:**
Users are incorrectly redirected to the configurator screen instead of the website page. However, refreshing the page correctly redirects to the home screen as the server-side route is triggered on reload.

**Reason:**
The issue started in Odoo 16. Until Odoo 15, redirection to the configurator route is handled using ir.actions.act_url, which triggered a full page reload, ensuring the server route executed.
From Odoo 16 onwards, this action is removed, and a direct client action is attached. Within `configurator.js`, navigation is now handled using the `history.pushState` method which replace the current url and does not trigger a reload. As a result, even when navigating to the configurator route, the server route is not executed, leading to incorrect redirection.

**Fix:**
Added a check in configurator.js to verify the configurator status. If it is true, the user is redirected to the website page instead of the configurator. Otherwise, the normal configurator flow continues.

**Key Changes:**
1. In configurator_init, added a check: if configurator_done is True, set the default theme using button_choose_theme and store its result (a dict containing the next action to execute) as redirect_url.
2. In the Configurator component, added redirect_url to the store, and inside the onWillStart method, checked if redirect_url exists. If it does, redirect to the home screen using doAction.

This PR ensures the correct redirection behavior when users follow the Industries installation flow.

task-4555467

### CODE REVIEW

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 1]
```diff
@@ -629,7 +629,11 @@ export class Configurator extends Component {
 
         onWillStart(async () => {
             this.websiteId = (await this.orm.call('website', 'get_current_website')).match(/\d+/)[0];
-
+            const [configurator_status] = await this.orm.searchRead("website", [["id", "=", this.websiteId]], ["configurator_done"]);
+            if (configurator_status && configurator_status.configurator_done) {
```
Comment (shsa-odoo) [inline addons/website/static/src/client_actions/configurator/configurator.js:633]:
```suggestion
            if (configurator_status?.configurator_done) {
```

**Review by shsa-odoo — COMMENTED** [review]
Not a big fan of making multiple orm calls but we need current website id and its configurator_done status.
Looks good ! Kindly make this small change.

File: addons/website/static/src/client_actions/configurator/configurator.js (hunk 1 above)
Comment (chdh-odoo) [reply addons/website/static/src/client_actions/configurator/configurator.js:633]: I'm on 16 branch and optional chaining operator is not supported! It is throwing eslint error on runbot. Thanks.

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 2]
```diff
@@ -629,7 +629,11 @@ export class Configurator extends Component {
 
         onWillStart(async () => {
             this.websiteId = (await this.orm.call('website', 'get_current_website')).match(/\d+/)[0];
-
+            const [configurator_status] = await this.orm.searchRead("website", [["id", "=", this.websiteId]], ["configurator_done"]);
```
Comment (msh-odoo) [inline addons/website/static/src/client_actions/configurator/configurator.js:632]: Why separate call, why not manage it in ```configurator_init```?

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 3]
```diff
@@ -629,8 +629,11 @@ export class Configurator extends Component {
 
         onWillStart(async () => {
             this.websiteId = (await this.orm.call('website', 'get_current_website')).match(/\d+/)[0];
-
             await store.start(() => this.getInitialState());
+            if (store.is_configurator_done) {
+                this.router.redirect('/');
+                return Promise.reject();
```
Comment (msh-odoo) [inline addons/website/static/src/client_actions/configurator/configurator.js:635]: this line not needed

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 4]
```diff
@@ -629,8 +629,11 @@ export class Configurator extends Component {
 
         onWillStart(async () => {
             this.websiteId = (await this.orm.call('website', 'get_current_website')).match(/\d+/)[0];
-
             await store.start(() => this.getInitialState());
+            if (store.is_configurator_done) {
+                this.router.redirect('/');
```
Comment (msh-odoo) [inline addons/website/static/src/client_actions/configurator/configurator.js:634]:
```suggestion
                this.router.redirect("/");
```

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 5]
```diff
@@ -630,8 +630,11 @@ export class Configurator extends Component {
 
         onWillStart(async () => {
             this.websiteId = (await this.orm.call('website', 'get_current_website')).match(/\d+/)[0];
-
             await store.start(() => this.getInitialState());
+            if (store.is_configurator_done) {
```
Comment (SergeBayet) [inline addons/website/static/src/client_actions/configurator/configurator.js:634]:
```suggestion
            if (store.configurator_done) {
```

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 6]
```diff
@@ -630,8 +630,11 @@ export class Configurator extends Component {
 
         onWillStart(async () => {
             this.websiteId = (await this.orm.call('website', 'get_current_website')).match(/\d+/)[0];
-
```
Comment (SergeBayet) [inline addons/website/static/src/client_actions/configurator/configurator.js:633]: unnecessary diff.

**Review by SergeBayet — CHANGES_REQUESTED** [review]
Looks great. :+1: Some remarks though to keep `configurator_done` naming

**Comment by SergeBayet** [comment]
Switch your PR as ready for review please. Thanks :pray:

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 7]
```diff
@@ -630,8 +630,11 @@ export class Configurator extends Component {
...
             await store.start(() => this.getInitialState());
+            if (store.is_configurator_done) {
+                this.router.redirect("/");
```
Comment (SergeBayet) [inline addons/website/static/src/client_actions/configurator/configurator.js:635]: When I test this I have this error `redirect` is not a function. Could you test? I'm a little bit confused because the documentation mention (https://www.odoo.com/documentation/17.0/developer/reference/frontend/services.html#redirect) but it doesn't appear in the codebase.

Comment (SergeBayet) [reply addons/website/static/src/client_actions/configurator/configurator.js:635]: @chdh-odoo Ok You've re-targeted this PR from 16.0 to 17.0. In 17.0, `redirect` was removed. You'll have to use something else (`pushState` probably)

**Review by SergeBayet — CHANGES_REQUESTED** [review]

File: addons/website/static/src/client_actions/configurator/configurator.js (hunk 7 above)
Comment (chdh-odoo) [reply addons/website/static/src/client_actions/configurator/configurator.js]: Yes, as an alternative, I went with the `doAction` method here’s a quick explanation, why i used that,

i didn’t go with `window.location.assign("/")` because it causes the configurator screen to flash for a second or two before redirecting, which isn’t ideal. (before re-targeting my branch I was rejecting the onwillstart promise after redirect to home screen, which worked in 16.0 but  did not worked in 17 so I'm not using that)

so I used doAction method, which is also used inside `skipConfigurator` method, but I couldn’t call `skipConfigurator` directly since it takes you to the theme selection screen instead of the home screen. On the `master` branch, that’s already fixed (see this PR: [#189142](https://github.com/odoo/odoo/pull/189142/files)), so in master I can directly call `skipConfigurator` if configurator_done is true :)

File: addons/website/models/website.py [hunk 8]
```diff
@@ -398,6 +400,9 @@ def configurator_init(self):
         r['logo'] = False
         if not company.uses_default_logo:
             r['logo'] = company.logo.decode('utf-8')
+        if current_website.configurator_done:
+            r['redirect_url'] = theme.button_choose_theme()
```
[the remark this answers is not in the document]
Comment (chdh-odoo) [reply addons/website/models/website.py:404]: indeed, thanks for pointing it out :)

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 9]
```diff
@@ -686,6 +690,8 @@ export class Configurator extends Component {
         const r = {
             industries: results.industries,
             logo: results.logo ? 'data:image/png;base64,' + results.logo : false,
+            configurator_done: results.configurator_done,
+            redirect_url: results?.redirect_url,
```
[the remark this answers is not in the document]
Comment (chdh-odoo) [reply addons/website/static/src/client_actions/configurator/configurator.js]: i've changed this by adding redirect_url conditionally like below,  we only  add redirect_url if it exists
```
 const r = {
            industries: results.industries,
            logo: results.logo ? 'data:image/png;base64,' + results.logo : false,
            ...(results.redirect_url && { redirect_url: results.redirect_url }),
        };
        
```
        
let me know if there's a better way :)

**Comment by chdh-odoo** [comment]
@SergeBayet I've adapted the suggested changes. Thanks for your comments :)

File: addons/website/static/src/client_actions/configurator/configurator.js (hunk 9 above)
[the remark this answers is not in the document]
Comment (SergeBayet) [reply addons/website/static/src/client_actions/configurator/configurator.js]: Keep it simple :)
```
if (results.redirect_url) {
    r.redirect_url = results.redirect_url;
}
```

**Review by SergeBayet — CHANGES_REQUESTED** [review]
Just a nitpick and we're good to go :)

**Comment by sobo-odoo** [comment]
@robodoo delegate=SergeBayet

File: addons/website/static/src/client_actions/configurator/configurator.js [hunk 10]
```diff
@@ -686,6 +692,7 @@ export class Configurator extends Component {
         const r = {
             industries: results.industries,
             logo: results.logo ? 'data:image/png;base64,' + results.logo : false,
+            redirect_url: results.redirect_url
```
[the remark this answers is not in the document]
Comment (chdh-odoo) [reply addons/website/static/src/client_actions/configurator/configurator.js]: I've made this change.

**Review by SergeBayet — APPROVED** [review]

**Comment by SergeBayet** [comment]
@robodoo r+
