### ISSUE TITLE
Get " 'module' object has no attribute 'SavepointCase' " when use 'openerp-server -u all'

### ISSUE THREAD

**Issue by cysnake4713** [odoo/odoo#7458]
When use command 'openerp -d {dbname} -u all' to update all installed modules, I get:
 > File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/service/server.py", line 906, in preload_registries
    registry = RegistryManager.new(dbname, update_module=update_module)
  File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/registry.py", line 341, in new
    openerp.modules.load_modules(registry._db, force_demo, status, update_module)
  File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/loading.py", line 315, in load_modules
    modobj.update_list(cr, SUPERUSER_ID)
  File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/api.py", line 237, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/addons/base/module/module.py", line 654, in update_list
    handler.load_addons()
  File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/http.py", line 1241, in load_addons
    m = __import__('openerp.addons.' + module)
  File "/home/cysnake4713/pythonenv/tianv-erp/local/lib/python2.7/site-packages/openerp-8.0-py2.7.egg/openerp/modules/module.py", line 77, in load_module
    mod = imp.load_module('openerp.addons.' + module_part, f, path, descr)
  File "/home/cysnake4713/pythonenv/tianv-erp/odoo/addons/website_forum/__init__.py", line 5, in <module>
    import tests
  File "/home/cysnake4713/pythonenv/tianv-erp/odoo/addons/website_forum/tests/__init__.py", line 3, in <module>
    import common
  File "/home/cysnake4713/pythonenv/tianv-erp/odoo/addons/website_forum/tests/common.py", line 18, in <module>
    class TestForumCommon(common.SavepointCase):
> AttributeError: 'module' object has no attribute 'SavepointCase'

After a few more test, I find it happened everytime when you try to update any module

I think this is caused by commit 11ba468, @xmo-odoo

**Comment by xmo-odoo** [comment]
Can't repro locally and this doesn't really make sense, the `SavepointCase` import is static. The only explanation I can see is that you have somehow updated the modules and not the core, or you had a conflict which you resolved by rollbacking `openerp.tests.common.SavepointCase` (possibly amongst others). Either way you've got a desync somewhere between the code of website_forum and the code of openerp itself.

**Comment by cysnake4713** [comment]
I use virtualenv manage package
Formerly I update the new code in old virtual 	environment, I got this issue and #6742,
Today I create a new  virtual 	environment, everything is working great, #6742 is not a problem any more,

So I guess this one is caused by some depends  or virtualenv problem, not code problem, Thanks for your help. @xmo-odoo
