### PR TITLE
[FIX] project_task_model_mixin: keep domain a Domain in template branch

### PR DESCRIPTION
**Pull request by jeanschoenlaub**
In the `render_task_templates` branch, the `has_template_ancestor` step called `.toList({})`, turning `domain` into a plain list. It was only rebuilt into a `Domain` when a `default_project_id` was in context, so otherwise the trailing `domain.toList({})` threw `TypeError: domain.toList is not a function`.

Introduced in 694ea6a2fb60 (odoo/odoo#279015).

Fix: drop the premature `.toList({})` so `domain` stays a `Domain` until the single final conversion.

Appeared on many clickAll failures assigned to the JS team:

https://runbot.odoo.com/odoo/error/944607

### CODE REVIEW

**Comment by xavierbol** [comment]
I just rebase again to make sure the runbot builds target version 19.4 instead of master. 🙂
