### ISSUE TITLE
Regression on inverse method call

### ISSUE THREAD

**Issue by simahawk** [odoo/odoo#117559]
**Commit introducing the regression:** https://github.com/odoo/odoo/commit/36544651f2049bcf18777091dbf02c9631b33243

**Impacted versions:** 14.0, 15.0 16.0

**Steps to reproduce:** use a partial method for an inverse field property

Ex: https://github.com/OCA/server-env/blob/14.0/server_environment/models/server_env_mixin.py#L335

**Current behavior:** breaks like this

```
2023-04-04 06:33:21,973 895 CRITICAL odoo odoo.service.server: Failed to initialize database `odoo`. 
Traceback (most recent call last):
  File "/opt/odoo/odoo/tools/convert.py", line 677, in _tag_root
    f(rec)
  File "/opt/odoo/odoo/tools/convert.py", line 580, in _tag_record
    record = model._load_records([data], self.mode == 'update')
  File "/opt/odoo/odoo/models.py", line 4241, in _load_records
    records = self._load_records_create([data['values'] for data in to_create])
  File "/opt/odoo/odoo/models.py", line 4157, in _load_records_create
    return self.create(values)
  File "<decorator-gen-119>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo-venv/lib/python3.6/site-packages/odoo/addons/component_event/models/base.py", line 102, in create
    records = super(Base, self).create(vals_list)
  File "<decorator-gen-64>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/addons/base/models/ir_fields.py", line 534, in create
    recs = super().create(vals_list)
  File "<decorator-gen-13>", line 2, in create
  File "/opt/odoo/odoo/api.py", line 348, in _model_create_multi
    return create(self, arg)
  File "/opt/odoo/odoo/models.py", line 3919, in create
    fields[0].determine_inverse(batch_recs)
  File "/opt/odoo/odoo/fields.py", line 1207, in determine_inverse
    determine(self.inverse, records)
  File "/opt/odoo/odoo/fields.py", line 81, in determine
    if needle.__name__.find('__'):
AttributeError: 'functools.partial' object has no attribute '__name__'
``

**Expected behavior:** it should work as before as there's no reason to not support partial methods

**Comment by AbdelAzizMohamedMousa** [comment]
The issue seems to be related to a regression introduced in commit 3654465 that causes an error when using a partial method for an inverse field property. The error message suggests that the functools.partial object has no attribute 'name', which is required for the code to work.

To resolve this issue, one solution is to modify the code in the fields.py file to handle partial methods correctly. Specifically, the code should check if the needle object is a partial method and, if so, retrieve the name of the underlying function using the name attribute of the func attribute of the partial object.

Here's an example of how this could be implemented:
`def determine(needle, records):
    if isinstance(needle, partial):
        needle_name = needle.func.__name__
    else:
        needle_name = needle.__name__
    ...
`

By making this change, the code should be able to handle partial methods correctly and the error should be resolved.
