### ISSUE TITLE
ctrading a new user give a error

### ISSUE THREAD

**Issue by icf20** [odoo/odoo#23303]
Impacted versions:11

Steps to reproduce:
1 use this https://github.com/Yenthe666/InstallScript
2 try to create a new user

Current behavior:

baseurl/web/content/254-2b71f52/web.assets_backend.js:1250  error

Expected behavior:
create a new user
Video/Screenshot link (optional):

**Comment by grzekru** [comment]
`Error:
Uncaught TypeError: Cannot read property 'views' of undefined

http://localhost:8069/web/static/src/js/views/basic/basic_model.js:3518
Traceback:
TypeError: Cannot read property 'views' of undefined
    at Class._processX2ManyCommands (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:3518:30)
    at Class.applyDefaultValues (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:267:32)
    at Object.<anonymous> (http://localhost:8069/web/static/src/js/views/basic/basic_model.js:3324:29)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)
    at Object.fireWith [as resolveWith] (http://localhost:8069/web/static/lib/jquery/jquery.js:3231:49)
    at Object.deferred.(anonymous function) [as resolve] (http://localhost:8069/web/static/lib/jquery/jquery.js:3321:62)
    at Object.<anonymous> (http://localhost:8069/web/static/src/js/services/ajax_service.js:13:33)
    at Object.<anonymous> (http://localhost:8069/web/static/lib/jquery/jquery.js:3276:89)
    at fire (http://localhost:8069/web/static/lib/jquery/jquery.js:3119:58)`

**Comment by grzekru** [comment]
broken by ad1cceb4fbd2f054af647833bd34e4e06012bb6c

**Comment by sswapnesh** [comment]
I can confirm this bug.

![](https://image.prntscr.com/image/S_ZF7yNWRXGyLlP9zXQCzA.png)

**Comment by sswapnesh** [comment]
Same behavior at one more Place

![](https://image.prntscr.com/image/oJOWTZNDRFqIU6AV5ynoOg.png)

**Comment by AnilKesariya** [comment]
@grzekru : Any quick solution or temporary solution to resolve this problem?

**Comment by sergioalbuquerque** [comment]
Odoo..Oddo....Ohh dio....Same than me... someone?

**Comment by aab-odoo** [comment]
Hello,

This is a quick solution to fix the issue: https://github.com/odoo-dev/odoo/commit/71598a1ad47adec79679983e604ec1d92295b03b

I'll commit this in 11.0 this morning.

Sorry about that...
Regards

**Comment by AnilKesariya** [comment]
@aab-odoo : thanks for update.
