### PR TITLE
[FIX] l10n_it_edi: Correct function signature

### PR DESCRIPTION
**Pull request by LouisGobert**
The current call to `super()._get_proxy_identification()` was incorrect, because the parent method expects a 'company' argument.

Steps to reproduce:
 - Configure an Italian company
 - Install l10n_it_edi
 - Attempt to set up Peppol

This triggers:
TypeError: AccountEdiFormat._get_proxy_identification() missing 1 required positional argument: 'company'

The issue occurs following the addition of account_peppol, because
before that, no other EDI format existed besides fattura_pa, so the
condition in the if clause was never triggered.

Ticket [link](https://www.odoo.com/odoo/project.task/5405602)
opw-5405602

### CODE REVIEW

**Comment by lordkrandel** [comment]
- Exceptional merge due to the fact that `FP` wants `PEPPOL` to work in `16.0` even if it's not actively maintained any more.
- Tested and quite straightforward
- Blame check: Code was untouched since birth from `bfr` four years ago.

@robodoo r+

Thanks for the analysis effort and the surgical fix!
