### PR TITLE
[FIX] account_edi_ubl_cii: guard invoice in intracom delivery date logic

### PR DESCRIPTION
**Pull request by mkoeck**
### Description of the issue/feature this PR addresses:
A regression in account_edi_xml_ubl_bis (_ubl_get_delivery_node_from_delivery_address) references invoice.invoice_date in the intracom delivery branch even when invoice is not set.
This method is also used in sale-order UBL export flows (for example during quotation PDF generation from mail.compose.message), where vals.get('invoice') can be None.
Blame points to regression introduction in commit 0bf8df7d0a096cf8fe984c42d331404d473eeb71 (FP from f6c5aed52e00e807c4879e4139b116f1bea8282e).

### Current behavior before PR:
When the flow reaches sale-order BIS3 export without an invoice in vals, Odoo crashes with:

AttributeError: 'NoneType' object has no attribute 'invoice_date'

This raises an RPC_ERROR and breaks the mail composer / send flow

### Desired behavior after PR is merged:
The intracom delivery-date override is only applied when invoice exists and has invoice_date.
If invoice is missing (sale-order export context), no crash occurs, the delivery node is still generated safely, and mail composer/report generation completes normally.
Invoice export behavior remains unchanged for valid invoice contexts.

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

File: addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py [hunk 1]
```diff
@@ -514,7 +514,9 @@ def _ubl_get_delivery_node_from_delivery_address(self, vals):
         customer = vals['customer']
         supplier = vals['supplier']
         if (
-            customer.country_id.code in EUROPEAN_ECONOMIC_AREA_COUNTRY_CODES
+            invoice
+            and invoice.invoice_date
```
Comment (aboo-odoo) [inline addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py:518]: You shouldn't be able to export an invoice if it is not posted, meaning that `invoice_date` should always be set at this point. Thus, there is no need to check that there is an `invoice_date`. It would actually be better to trigger an error if it is missing since it means something went wrong up the stack and it's better to stop the blood bath here that let it slip through.

File: addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py
Comment (aboo-odoo) [inline addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py:510]: Maybe ? Instead of the double `if invoice`
```suggestion
if not invoice := vals.get('invoice'):
    return node

if invoice.delivery_date:
```

**Review by aboo-odoo — COMMENTED** [review]
Hello! Just one small comment 😄

File: addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py (hunk 1 above)
Comment (mkoeck) [reply addons/account_edi_ubl_cii/models/account_edi_xml_ubl_bis3.py:518]: I trust that you know this better but as far as I can see this piece of code is also triggered when printing a sale.order without invoice, and presumably also when you print a sale.order with an invoice in draft, in which case the invoice_date would not be filled.

Feels weird to raise an error when printing a sale.order just because the invoice is not confirmed yet.

If you say so, just let me know and I will raise a UserError if invoice is filled, but not invoice_date.
