### PR TITLE
[FIX] account_edi_ubl_cii: guard enterprise-only deferred dates

### PR DESCRIPTION
**Pull request by RicardCForgeFlow**
`_cii_get_billing_specified_period_node` reads `deferred_start_date` and `deferred_end_date` directly, but those fields only exist when the enterprise accounting app is installed. Exporting Factur-X on Community raises:

```
AttributeError: 'account.move.line' object has no attribute 'deferred_start_date'
```

This currently breaks the CI of OCA/l10n-spain on 18.0: every pull request errors in the `l10n_es_facturae_face` and `l10n_es_pos_sii` tests.

Introduced in 9fc11bbc9 (`[REF] account_edi_ubl_cii, *: refactoring of the export of factur-x`), which rewrote this code into the new `account_edi_cii.py`. The code it replaced did guard the fields, as the rest of the module still does:

- [`account_edi_xml_cii_facturx.py:209`](https://github.com/odoo/odoo/blob/167e83374756c4c38bc46eb96763dfbd8cb8de6f/addons/account_edi_ubl_cii/models/account_edi_xml_cii_facturx.py#L209) -> `line._fields.get('deferred_start_date')`
- [`account_edi_ubl.py:1277`](https://github.com/odoo/odoo/blob/167e83374756c4c38bc46eb96763dfbd8cb8de6f/addons/account_edi_ubl_cii/models/account_edi_ubl.py#L1277) -> `base_line.get('deferred_start_date')`

Same guard applied here.

### CODE REVIEW

**Comment by RicardCForgeFlow** [comment]
Duplicate of [#286245](https://github.com/odoo/odoo/pull/286245), which also covers the two import paths. Closing.
