### ISSUE TITLE
[17.0] Error when loading Odoo on Safari

### ISSUE THREAD

**Issue by traviswaelbro** [odoo/odoo#142022]
Impacted versions: 17.0, master (Community and Enterprise)

Steps to reproduce: Open any runbot instance using Safari (I am using Safari 15.2 (17612.3.6.1.6) on MacOS 12.1)

Current behavior:

<details>
    <summary>Error shown in Odoo GUI</summary>

```
The following modules failed to load because of an error, you may find more information in the devtools console:
@website/components/media_dialog/image_selector
The following modules are needed by other modules but have not been defined, they may not be present in the correct asset bundle:
@website_sale/js/sale_variant_mixin
@website_sale/js/website_sale
@website_sale/js/website_sale_utils
@website/js/content/website_root
@web_editor/js/wysiwyg/fonts
@web_editor/js/editor/odoo-editor/src/utils/utils
The following modules could not be loaded because they have unmet dependencies, this is a secondary error which is likely caused by one of the above problems:
@website_sale_renting/js/variant_mixin
@website_sale_renting/js/website_sale_renting
@website_sale_renting/js/website_sale_utils
@website/js/content/website_root_instance
root.widget
@web_editor/components/media_dialog/icon_selector
@web_editor/components/media_dialog/media_dialog
@web_unsplash/components/media_dialog/image_selector
@web_editor/js/common/grid_layout_utils
```
</details>

In Safari devtools console:

```
Error: Error while loading "@website/components/media_dialog/image_selector":
TypeError: Object.hasOwn is not a function. (In 'Object.hasOwn(objToPatch,"constructor")', 'Object.hasOwn' is undefined)
startModule — web.assets_frontend_minimal.min.js:11:267
startModules — web.assets_frontend_minimal.min.js:10
addJob — web.assets_frontend_minimal.min.js:7
define — web.assets_frontend_minimal.min.js:6:148
define
Global Code — web.assets_frontend_lazy.min.js:6704
Selected Element
<div class="position-fixed w-100 h-100 d-flex align-items-center flex-column bg-white overflow-auto modal" style="z-index: 10000;">…</div>
```

Expected behavior: Odoo website/login page is shown normally.

Video/Screenshot link (optional):

![image](https://github.com/odoo/odoo/assets/7907616/4a96c2d7-febf-4f0d-8d72-e6532a10611b)

Support ticket number submitted via odoo.com/help (optional): #3595648

**Comment by traviswaelbro** [comment]
I had another person check this on their computer and it works fine there. Unfortunately, I don't know their system specifics, but that at least suggests this is not a global issue with Safari.

**Comment by willmakenoise** [comment]
I get the same error using Mac OS 12.2 and Safari 15.3.
It however works on MacOS 13.0 and 13.5.2 with Safari 16.1 and 16.6.

**Comment by pierrelocus** [comment]
Same error on Chrome on Android. Do we have a followup on that ?

**Comment by rbiojout** [comment]
Same here on iPad with latest version

**Comment by gentoair** [comment]
same Odoo 17 Online Huawei Mate 40 Pro Firefox und Iphone 10 Safari and Chrome

**Comment by wonrence** [comment]
I met the same problem with chrome, however there is no issues when I use the latest safari and edge . i try to re-install chrome, it works fine, but after i reboot the PC, it cames again.
I do not think it's big issues. but I will do more test

**Comment by gentoair** [comment]
> I met the same problem with chrome, however there is no issues when I use the latest safari and edge . i try to re-install chrome, it works fine, but after i reboot the PC, it cames again. I do not think it's big issues. but I will do more test

Have you found the reason? I've noticed, that i have issue in Built-In Browser if i open the link from Instagram(Huawei mate 40 Pro), but it's ok with an extern Browser. The old iphone 10 have the issue in each browser. Maybe it's timing problem on old devices/browsers? website/components/media_dialog/image_selector

**Comment by benzidane027** [comment]
pip install libsass

**Comment by traviswaelbro** [comment]
In my case, we are running Odoo via Docker and it already has `libsass==0.20.1` installed.

**Comment by wouter-tricore** [comment]
Same issue here with Odoo source install with libsass==0.20.1 installed.

**Comment by tuanace** [comment]
Yes, it seem to have problem with old devices, in my case iphone 12 os version 14.7

**Comment by pierrelocus** [comment]
I used Firefox, at least we could use the device.. anyway

**Comment by halecorp** [comment]
same issues. multiple customers are having issues using website with safari.

**Comment by sambeauvois** [comment]
Hi,

I have the same issue, odoo 17.1 online "standard". 

I have the error on the website and can't log, thats a blocker for my project.

I tried updating the website module but I stil have the issue.

![20240403_185053](https://github.com/odoo/odoo/assets/141645/a788e98e-7df4-4367-8061-4c8eaaa2a731)

did someone found a workaround ?

**Comment by unique4** [comment]
I believe because of this line
https://github.com/odoo/odoo/blob/a1b8cfec431fe2393ae19719f886fb03c0a8b5e8/addons/web/static/src/core/utils/patch.js#L40
Object.hasOwn does not support old version browser, need a fallback to Object.prototype.hasOwnProperty()

**Comment by unique4** [comment]
#160758 Oh dev found it

**Comment by rdeodoo** [comment]
Indeed.. Thank you for your report. The fix will most likely go through ASAP.
Sadly, you reported the issue 6 months ago but it never reached the website team.
Feel free to ping the @odoo/rd-website team explicitly whenever you face such a website issue, we will happily have a look.

**Comment by wonrence** [comment]
Great! that is very helpful. Thank you all!

**Comment by traviswaelbro** [comment]
@rdeodoo Thank you all for the update. I can confirm I'm able to view and interact with Odoo's website _(can complete an order, view portal, etc. with no problem)_, but I'm getting a different issue after logging into Odoo's backend.

I can create a separate issue report for this, but should I ping @odoo/rd-website as you suggested or a different part of the Odoo team since it is no longer a website frontend issue?

> The following modules failed to load because of an error, you may find more information in the devtools console:
> * @mail/js/onchange_on_keydown

> Error: Error while loading "@mail/js/onchange_on_keydown":
> TypeError: Object.hasOwn is not a function. (In 'Object.hasOwn(objToPatch,"constructor")', 'Object.hasOwn' is undefined)

**Comment by rdeodoo** [comment]
For the backend, the policy is completely different. Odoo clients (backend) are supposed to run Odoo on an up to date browser. We don't support old browsers in backend.

Supporting old browser or paying attention to retro-compatibility is something only the frontend cares about

**Comment by jak-4** [comment]
The following modules failed to load because of an error, you may find more information in the devtools console:
@custom_addons/js/google_play_button
