### ISSUE TITLE
[15.0] AttributeError: 'QWeb' object has no attribute 'env'

### ISSUE THREAD

**Issue by obayit** [odoo/odoo#80655]
Impacted versions:
15.0

Current behavior:
I get his error when I visit `/web/database/selector`:
```
sets_frontend HTTP/1.0" 200 - 10 0.001 0.015
2021-12-01 08:03:42,883 19306 INFO main werkzeug: 94.49.30.236 - - [01/Dec/2021 08:03:42] "GET /web/database/selector HTTP/1.0" 500 - 6 0.004 
0.018
2021-12-01 08:03:42,891 19306 ERROR main werkzeug: Error on request:
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 180, in _compile
    self._compile_node(element, _options, 1) +
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 955, in _compile_directive_content
    if self.env.context.get('preserve_comments'):
AttributeError: 'QWeb' object has no attribute 'env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 810, in dispatch
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 955, in _compile_directive_content
    if self.env.context.get('preserve_comments'):
AttributeError: 'QWeb' object has no attribute 'env'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 237, in _dispatch
    result = request.dispatch()
  File "/opt/odoo/odoo/odoo/http.py", line 810, in dispatch
    r = self._call_function(**self.params)
  File "/opt/odoo/odoo/odoo/http.py", line 359, in _call_function
    return checked_call(self.db, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/service/model.py", line 94, in wrapper
    return f(dbname, *args, **kwargs)
  File "/opt/odoo/odoo/odoo/http.py", line 348, in checked_call
    result = self.endpoint(*a, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 916, in __call__
    return self.method(*args, **kw)
  File "/opt/odoo/odoo/odoo/http.py", line 535, in response_wrap
    response = f(*args, **kw)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1079, in selector
    return self._render_template(manage=False)
  File "/opt/odoo/odoo/addons/web/controllers/main.py", line 1074, in _render_template
    return QWeb()._render(html.document_fromstring(template), d, load=load)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 132, in _render
    render_template = self._compile(template, options)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 187, in _compile
    raise QWebException("Error when compiling xml template", self, options,
Exception

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 306, in run_wsgi
    execute(self.server.app)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/serving.py", line 294, in execute
    application_iter = app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 110, in application
    return ProxyFix(application_unproxied)(environ, start_response)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/proxy_fix.py", line 232, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/odoo/service/wsgi_server.py", line 87, in application_unproxied
    result = odoo.http.root(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1313, in __call__
    return self.dispatch(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1279, in __call__
    return self.app(environ, start_wrapped)
  File "/usr/local/lib/python3.8/dist-packages/werkzeug/middleware/shared_data.py", line 220, in __call__
    return self.app(environ, start_response)
  File "/opt/odoo/odoo/odoo/http.py", line 1489, in dispatch
    result = ir_http._dispatch()
  File "/opt/odoo/odoo/addons/auth_signup/models/ir_http.py", line 19, in _dispatch
    return super(Http, cls)._dispatch()
  File "/opt/odoo/odoo/addons/web_editor/models/ir_http.py", line 21, in _dispatch
    return super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/addons/utm/models/ir_http.py", line 29, in _dispatch
    response = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/addons/http_routing/models/ir_http.py", line 515, in _dispatch
    result = super(IrHttp, cls)._dispatch()
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 241, in _dispatch
    return cls._handle_exception(e)
  File "/opt/odoo/odoo/addons/utm/models/ir_http.py", line 34, in _handle_exception
    response = super(IrHttp, cls)._handle_exception(exc)
  File "/opt/odoo/odoo/addons/http_routing/models/ir_http.py", line 611, in _handle_exception
    return super(IrHttp, cls)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/addons/base/models/ir_http.py", line 209, in _handle_exception
    return request._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 748, in _handle_exception
    return super(HttpRequest, self)._handle_exception(exception)
  File "/opt/odoo/odoo/odoo/http.py", line 301, in _handle_exception
    raise exception.with_traceback(None) from new_cause
odoo.addons.base.models.qweb.QWebException: 'QWeb' object has no attribute 'env'
Traceback (most recent call last):
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 180, in _compile
    self._compile_node(element, _options, 1) +
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 958, in _compile_directive_content
    body.extend(self._compile_node(item, options, indent))
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 346, in _compile_node
    return self._compile_static_node(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 701, in _compile_static_node
    body = self._compile_directive_content(el, options, indent)
  File "/opt/odoo/odoo/odoo/addons/base/models/qweb.py", line 955, in _compile_directive_content
    if self.env.context.get('preserve_comments'):
AttributeError: 'QWeb' object has no attribute 'env'

Error when compiling xml template
AttributeError: 'QWeb' object has no attribute 'env'
Template: <Element html at 0x7f1bba065f90> - - -
```

What can be the cause of such errors?

**Comment by sammie520** [comment]
Caused by this commit

https://github.com/odoo/odoo/commit/d17d8523c039ef574062ec20e74d872258e6487f#diff-93886ce47469742e6789e530da959bb35349a9837bebdb51076ff672cd96a8e7

**Comment by wamdam** [comment]
This was introduced in d17d8523c03.
cd odoo
git co 8778c10bc18
and it will work again

**Comment by obayit** [comment]
how did this pass the test?

**Comment by odony** [comment]
Fixed by #80666, thanks for reporting
