### PR TITLE
[FIX] project_task_model_mixin: keep domain a Domain in template branch

### PR DESCRIPTION
**Pull request by jeanschoenlaub**
When the `Templates` filter is active (`render_task_templates` context), the `has_template_ancestor` step reassigned `domain` to the result of `.toList({})`, turning it into a plain list. That list was only rebuilt into a `Domain` inside the `if (projectId)` branch, so when no `default_project_id` was in context (e.g. the Tasks Analysis report, `report.project.task.user`), the trailing `domain.toList({})` ran on an array and threw:

    TypeError: domain.toList is not a function

The crash is deterministic per view+context, but surfaced as a flaky clickAll error: the same latent bug is reachable from many views using this mixin, and paths reaching them with a `default_project_id` don't crash, so which coordinate trips first varies between runs.

The premature `.toList({})` was introduced in 694ea6a2fb60 (odoo/odoo#279015).

Fix: drop it so `domain` stays a `Domain` through both branches down to the single, intentional conversion at the end of the method.

runbot error: https://runbot.odoo.com/odoo/error/944672

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Comment by jeanschoenlaub** [comment]
Merged here
