### PR TITLE
[FIX] payment: timezone of online payment invoice

### PR DESCRIPTION
**Pull request by HANNICHE-Walid**
Steps to reproduce:
-run odoo using faketime
(TZ=UTC faketime -m '2021-06-19 01:33:00' python3 ./odoo/odoo-bin --addons-path=./custom,./odoo/addons,./enterprise/ -d db_name --dev xml --smtp=localhost --smtp-port=1025 --max-cron-threads=0) (equivalent to 2021-06-18 18:33 PST)
-enable test payment provider and automatic invoice in settings
-set user timezone in preference to America/Los_Angeles 
-create a subscription and send quotation by mail
-open customer preview
-copy link to a private window in the browser (user not loged in)
-sign and pay
-invoice date is 19/06/2021 (instead of 18/06/2021 when user logged in)

Bug:
when the user is not logged in, the timezone defaults to UTC

Fix:
when user isn't logged in, set the timezone to customer preference and fallback to the sales person timezone

opw-2356448

### CODE REVIEW

**Review by AntoineVDV — COMMENTED** [review]
Hello, could you detail the problem and your solution a bit more? For example, when do you need to read `self.sale_order_ids.create_uid.tz`, and why is it done in the `payment` module and not `sale`?

**Comment by HANNICHE-Walid** [comment]
hi @AntoineVDV when automatic invoice is enabled a successful payment creates an invoice 
if the payment is made for exemple at 18:33 PST (equivalent  to 01:33 UTC of the next day) the created invoice has the wrong date (next day) if the user is not logged in (accessed the payment portal with a token via the link on the email) 

when the user is logged in `tz` is set in the context 
this fix will set tz to the customer preference if possible `self.partner_id.tz `
else default to the salesman  `self.sale_order_ids.create_uid.tz`

this will ensure the appropriate date is set on the invoice

**Comment by AntoineVDV** [comment]
Ok I see. However there is no such field `sale_order_ids` in the module `payment`, only in `sale` which depends on `payment`. Your fix should therefore add a well-place override to select the timezone.

**Comment by HANNICHE-Walid** [comment]
@AntoineVDV  you're right `sale_order_ids` is added to `payment.transaction` in the sale module
I added a check to see if the attribute is set on that model

**Comment by AntoineVDV** [comment]
@HANNICHE-Walid I get that it quickly addresses your issue, but it's very bad practice. If we were to choose this solution every time we have a similar issue, we'd only have the `base` module.

Instead, please do:
> Your fix should therefore add a well-place override to select the timezone.

**Comment by HANNICHE-Walid** [comment]
@AntoineVDV sorry I hadn't understood you at first, it's fixed now

**Comment by AntoineVDV** [comment]
@HANNICHE-Walid Thanks :)

As I understand it, this faulty behavior only occurs with Sales' automatic invoice feature. Shouldn't you make your fix in only the `sale` module then? And wouldn't that be better to do it inside `_invoice_sale_orders`?

**Comment by HANNICHE-Walid** [comment]
@AntoineVDV actually the `_reconcile_after_transaction_done` in payment modifies the invoice date when posting it

**Comment by HANNICHE-Walid** [comment]
I also added the fix in payment to prevent that issue from happening when paying an invoice online when the sales module isn't installed

File: addons/payment/models/payment_acquirer.py [hunk 1]
```diff
@@ -816,6 +816,10 @@ def _set_transaction_done(self):
         })
 
     def _reconcile_after_transaction_done(self):
+        # set timezone if customer not logged in
+        timezone = self.env.context.get('tz') or self.partner_id.tz 
+        self = self.with_context(tz=timezone)
```
Comment (AntoineVDV) [inline addons/payment/models/payment_acquirer.py:821]:
```suggestion
        # Post invoices with the correct timezone by preventing it from defaulting to UTC when the
        # user is not logged in.
        self = self.with_context(tz=self.env.context.get('tz') or self.partner_id.tz)
```

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
Ok, now that the issue is clearly explained here, let's make it clear in the code too because it clearly requires some explanations.

**Comment by HANNICHE-Walid** [comment]
hi @AntoineVDV I added a fall back to the company timezone if the customer timezone is not set 
also added the tests

File: addons/payment/tests/test_invoices.py [hunk 2]
```diff
@@ -0,0 +1,76 @@
+# -*- coding: utf-8 -*-
+
+from odoo.addons.account.tests.account_test_savepoint import AccountTestInvoicingCommon
+from freezegun import freeze_time
+import datetime
```
Comment (AntoineVDV) [inline addons/payment/tests/test_invoices.py:5]: https://www.odoo.com/documentation/master/contributing/development/coding_guidelines.html#imports

File: addons/sale/models/payment.py [hunk 3]
```diff
@@ -110,6 +110,9 @@ def _reconcile_after_transaction_done(self):
             tx._check_amount_and_confirm_order()
         # send order confirmation mail
         sales_orders._send_order_confirmation_mail()
+        # set timezone if customer not logged in
```
Comment (AntoineVDV) [inline addons/sale/models/payment.py:113]: Comment https://github.com/odoo/odoo/pull/100548?notification_referrer_id=NT_kwDOAPKQ7bM0NDMxMzYxOTMzOjE1ODk2ODEz#discussion_r978386684 was referring to this line too.

**Review by AntoineVDV — CHANGES_REQUESTED** [review]
@HANNICHE-Walid Don't forget to deal with https://github.com/odoo/odoo/pull/100440 first. I will not merge this one until you deal with the forward-port.
Also, your test does not pass.

@Feyensv Could you have a look at the test in `sale`?

**Comment by HANNICHE-Walid** [comment]
> @HANNICHE-Walid Don't forget to deal with #100440 first. I will not merge this one until you deal with the forward-port. Also, your test does not pass.

@AntoineVDV sorry about that one I thought there was an issue with the test, turns out variable name had been changed.

I've made the requested changes  on this PR

File: addons/sale/tests/test_payment_automatic_invoice.py [hunk 4]
```diff
@@ -0,0 +1,77 @@
...
+        super(PaymentTest, cls).setUpClass()
+        cls.setUpClassicProducts()
+
+        cls.env['ir.config_parameter'].sudo().set_param('sale.automatic_invoice', True)
+
+        journal = cls.env['account.journal'].create({'type': 'bank', 'name': 'bank', 'code': 'BANK'})
+        cls.payment_test = cls.env.ref('payment_test.payment_acquirer_test').create({
+            'name': "test",
+            'journal_id': journal.id,
+        })
```
Comment (Feyensv) [inline addons/sale/tests/test_payment_automatic_invoice.py:20]: Why a new test class ?
Why a class setup if there is only one test ?
Why is the class named 'PaymentTest' ?

File: addons/sale/tests/test_payment_automatic_invoice.py [hunk 5]
```diff
@@ -0,0 +1,77 @@
...
+class PaymentTest(TestCommonSaleNoChart):
+    @classmethod
+    def setUpClass(cls):
+        super(PaymentTest, cls).setUpClass()
+        cls.setUpClassicProducts()
+
+        cls.env['ir.config_parameter'].sudo().set_param('sale.automatic_invoice', True)
+
+        journal = cls.env['account.journal'].create({'type': 'bank', 'name': 'bank', 'code': 'BANK'})
+        cls.payment_test = cls.env.ref('payment_test.payment_acquirer_test').create({
```
Comment (Feyensv) [inline addons/sale/tests/test_payment_automatic_invoice.py:17]:
```suggestion
        cls.payment_test = cls.env.ref('payment_test.payment_acquirer_test').create({
```
What's the use of referencing a record to call `create` on it?

File: addons/sale/tests/test_payment_automatic_invoice.py [hunk 6]
```diff
@@ -0,0 +1,77 @@
...
+            'name': "test",
+            'journal_id': journal.id,
+        })
+
+
+    def _create_transfer(self):
```
Comment (Feyensv) [inline addons/sale/tests/test_payment_automatic_invoice.py:23]:
```suggestion
    def _create_transaction(self):
```

**Review by Feyensv — CHANGES_REQUESTED** [review]

**Comment by HANNICHE-Walid** [comment]
@Feyensv thanks for the feedback I fixed the tests

File: addons/sale/models/payment.py [hunk 7]
```diff
@@ -110,6 +110,8 @@ def _reconcile_after_transaction_done(self):
             tx._check_amount_and_confirm_order()
         # send order confirmation mail
         sales_orders._send_order_confirmation_mail()
+        # Create invoices with the correct timezone by preventing it from defaulting to UTC when the user is not logged in.
+        self = self.with_context(tz=self.env.context.get('tz') or self.partner_id.tz or self.sale_order_ids.user_id.tz)
```
Comment (Feyensv) [inline addons/sale/models/payment.py:114]: Well, in fact, this is wrong now that i read it more attentively.
1) self can contain multiple records, which means `self.partner_id.tz` will raise.  And that the context change here is not right, cause you may want different tz contexts for different transactions reconciliations.
2) is the fallback on the salesman really useful?  Seems strange to me, and would break if multiple orders are linked to the transaction. why can't you follow the same tz logic as in payment and fallback on the company tz ?

Comment (HANNICHE-Walid) [reply addons/sale/models/payment.py:114]: @Feyensv you're right I haven't thought about the case of multiple transactions.
I was using the salesman before thinking of using the company tz, it seems redundant now. I'll delete the changes made to the sale module and its tests and edit the fix on payment to apply the tz for each transaction individually.

**Comment by HANNICHE-Walid** [comment]
hi @AntoineVDV I have fixed the PR to take into consideration multiple transacations and added the tests

**Comment by Feyensv** [comment]
@smetl Can I have your thoughts on this problem ?
This fix goes a bit too wild imho, it's kind of strange we have to post invoices one by one to make sure the invoice is properly posted in the timezone of the customer :thinking:.
Either it's a true problem, and then it should probably be managed directly in the account code, or it's not but I find it strange to slow down the post-processing of transactions (it's already causing a lot of problems) to fix a specific tz problem.  I guess there should be other places where invoices are automatically posted (and where the tz might not be set in the context or be the wrong one).

**Comment by smetl** [comment]
@Feyensv Everywhere in accounting, we are using `context_today` that is getting the timezone from context, then the current user. This seems more correct to me than taking the timezone of the customer. In fine, the only thing you want is to get the today UTC generated by the server. In case of the user is not logged, there should be a code somewhere in the portal code guessing the timezone of the user. But it shouldn't be made by hand for every business flows.

**Comment by Feyensv** [comment]
And what about CRONs ? :thinking:
Is it expected/a problem when invoices are generated with the superuser tz ?

**Comment by HANNICHE-Walid** [comment]
@smetl  even when the user is logged in shouldn't we always use the company tz for invoice creation and posting

**Comment by HANNICHE-Walid** [comment]
> This fix goes a bit too wild imho, it's kind of strange we have to post invoices one by one to make sure the invoice is properly posted in the timezone of the customer

we could do:

```python
    def _reconcile_after_transaction_done(self):
        if selfs.env.context.get('tz'):
            # Validate invoices automatically upon the transaction is posted.
            invoices = self.mapped('invoice_ids').filtered(lambda inv: inv.state == 'draft')
            invoices.post()

        # Create & Post the payments.
        payments = defaultdict(lambda: self.env['account.payment'])
        for trans in self:
            company = trans.acquirer_id.company_id
            if not selfs.env.context.get('tz'):
                # Post invoices with the correct timezone
                # by preventing it from defaulting to UTC when the user is not logged in.
                invoices = trans.mapped('invoice_ids').filtered(lambda inv: inv.state == 'draft')
                invoices.with_context(tz=trans.partner_id.tz or company.partner_id.tz).post()
```

**Comment by Feyensv** [comment]
Well, i think the only case where we might have a tz in the context is when we are only processing one transaction.  Still potentially slowing down the cron when there is a lot of transactions ...

**Comment by AntoineVDV** [comment]
Hi @HANNICHE-Walid,

> I have made that fix at the website controller level so it won't affect the cron

It doesn't seem like an appropriate place for the fix: it's too high in the call stack to fix the invoice-related problem resiliently. As a matter. Indeed, this solution will no longer hold in one of the more recent versions of Odoo.

Speaking of which, I checked the related ticket, and this issue was reported internally ages ago. This raises two questions:
- Is a fix still needed? As frustrating as this question can be, it's time to ask it ourselves, given how this PR has been running in circles. Sometimes, the bug has been indirectly resolved, and sometimes it's better not to fix it at all.
- If it is needed, shouldn't it be made in a more recent version? odoo.com is about to upgrade to Odoo 16.0. Target 13.0 which is no longer supported doesn't make much sense anymore.

**Comment by HANNICHE-Walid** [comment]
In version 16.0 the bug doesn't seem to happen anymore.
from my understanding this bug is mostly an issue for the subscription module where payments made at the end of month are incorrectly reported on the following one.
