### PR TITLE
[FIX] mass_mailing: mobile preview error

### PR DESCRIPTION
**Pull request by ande-odoo**
Current behavior:
---
When trying to preview a mailing template
with the debug mode enabled, there is an error:
Invalid props for component

Steps to reproduce:
---
1. Enable debug mode with assets
2. Go to Email Marketing
3. Create a new Mailing
4. Select a template
5. In the Editor, click on the mobile icon
6. ... 'preview' is not a function

Cause of the issue:
---
Caused by https://github.com/odoo/odoo/commit/13b3f8af4b55d32912b698ae1672be9e144cb775

opw-3702901

---
I confirm I have signed the CLA and read the PR guidelines at www.odoo.com/submit-pr

### CODE REVIEW

**Review by nle-odoo — APPROVED** [review]
looks good to me

@hubvd says this is clearly meant to be a string looking at the `const isMarkup = ...`

**Comment by ande-odoo** [comment]
@odoo/rd-sm-customer Could I get a review ? Thanks !

**Comment by nle-odoo** [comment]
```py
Or does "markup" inherit from String and thus will work with just "String" ?
```
as far as I can tell from:

https://github.com/odoo/odoo/blob/b104a50d6d7fbc07fde8de81a4e1935e540214e5/addons/web/static/lib/owl/owl.js#L323-L331

markup is a method and it should have been Markup instead and but it probably work as you say because Markup inherits from String

**Comment by awa-odoo** [comment]
Can be just "String", then, after than LGTM, thanks for the details @nle-odoo !

**Comment by ande-odoo** [comment]
Hi @odoo/rd-sm-customer @awa-odoo Could I get a R+ ? Thanks !

**Review by awa-odoo — APPROVED** [review]

**Comment by awa-odoo** [comment]
@robodoo delegate=@ande-odoo

**Comment by ande-odoo** [comment]
@robodoo r+
